"""The schema as the running server has it, squashed into one revision.

The deployed database is stamped `5f2b94d0e3a8`, so this never runs there -- it
exists so a fresh install reaches the same starting point, and so the revisions
after it have one linear parent instead of twenty files nobody reads.

Revision ID: 5f2b94d0e3a8
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "5f2b94d0e3a8"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coastal_segment",
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("center_lat", sa.Float(), nullable=False),
        sa.Column("center_lon", sa.Float(), nullable=False),
        sa.Column("length_km", sa.Float(), nullable=False),
        sa.Column("coastline_orientation_deg", sa.Float(), nullable=True),
        sa.Column("path", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_coastal_segment_external_id",
        "coastal_segment",
        ["external_id"],
        unique=True,
    )
    op.create_table(
        "drift_release",
        sa.Column("release_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_version", sa.String(length=16), nullable=False),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_drift_release_dedup",
        "drift_release",
        ["release_at", "model_version"],
        unique=True,
    )
    op.create_index(
        op.f("ix_drift_release_release_at"),
        "drift_release",
        ["release_at"],
        unique=False,
    )
    op.create_table(
        "grid_cell",
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("elevation_m", sa.Float(), nullable=False),
        sa.Column("distance_to_coast_km", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_grid_cell_dedup", "grid_cell", ["lat", "lon"], unique=True)
    op.create_table(
        "ingest_coverage",
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ingest_coverage_dedup", "ingest_coverage", ["kind", "day"], unique=True
    )
    op.create_table(
        "job",
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "done", "failed", name="jobstatus"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("not_before", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_kind"), "job", ["kind"], unique=False)
    op.create_index(op.f("ix_job_status"), "job", ["status"], unique=False)
    op.create_table(
        "marine_condition",
        sa.Column("valid_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("wind_speed_kmh", sa.Float(), nullable=True),
        sa.Column("wind_direction_deg", sa.Float(), nullable=True),
        sa.Column("current_speed_kmh", sa.Float(), nullable=True),
        sa.Column("current_direction_deg", sa.Float(), nullable=True),
        sa.Column("wave_height_m", sa.Float(), nullable=True),
        sa.Column("wave_direction_deg", sa.Float(), nullable=True),
        sa.Column("wave_period_s", sa.Float(), nullable=True),
        sa.Column("swell_height_m", sa.Float(), nullable=True),
        sa.Column("swell_direction_deg", sa.Float(), nullable=True),
        sa.Column("swell_period_s", sa.Float(), nullable=True),
        sa.Column("sea_surface_temperature_c", sa.Float(), nullable=True),
        sa.Column("sea_level_m", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_marine_condition_dedup",
        "marine_condition",
        ["valid_at", "lat", "lon", "source"],
        unique=True,
    )
    op.create_index(
        "ix_marine_condition_source_cell",
        "marine_condition",
        ["source", "lat", "lon"],
        unique=False,
    )
    op.create_index(
        op.f("ix_marine_condition_valid_at"),
        "marine_condition",
        ["valid_at"],
        unique=False,
    )
    op.create_table(
        "stranding",
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("species_scientific", sa.String(length=255), nullable=True),
        sa.Column("species_common", sa.String(length=255), nullable=True),
        sa.Column("individual_count", sa.Integer(), nullable=False),
        sa.Column("coordinate_uncertainty_m", sa.Float(), nullable=True),
        sa.Column("coordinate_precision_deg", sa.Float(), nullable=True),
        sa.Column("time_uncertainty_hours", sa.Float(), nullable=True),
        sa.Column("location_precision", sa.String(length=32), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_stranding_dedup", "stranding", ["source", "external_id"], unique=True
    )
    op.create_index(
        op.f("ix_stranding_recorded_at"), "stranding", ["recorded_at"], unique=False
    )
    op.create_table(
        "vessel_position",
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("mmsi", sa.String(length=16), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("ship_name", sa.String(length=128), nullable=True),
        sa.Column("flag", sa.String(length=8), nullable=True),
        sa.Column("gear_type", sa.String(length=64), nullable=True),
        sa.Column("vessel_type", sa.String(length=64), nullable=True),
        sa.Column("effort_hours", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_vessel_position_dedup",
        "vessel_position",
        ["mmsi", "recorded_at"],
        unique=True,
    )
    op.create_index(
        op.f("ix_vessel_position_mmsi"), "vessel_position", ["mmsi"], unique=False
    )
    op.create_index(
        op.f("ix_vessel_position_recorded_at"),
        "vessel_position",
        ["recorded_at"],
        unique=False,
    )
    op.create_table(
        "drift_daily",
        sa.Column("release_day", sa.Date(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("coastal_segment_id", sa.Integer(), nullable=False),
        sa.Column("model_version", sa.String(length=16), nullable=False),
        sa.Column("drift_index", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["coastal_segment_id"], ["coastal_segment.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_drift_daily_day", "drift_daily", ["day"], unique=False)
    op.create_index(
        "ix_drift_daily_dedup",
        "drift_daily",
        ["release_day", "day", "coastal_segment_id", "model_version"],
        unique=True,
    )
    op.create_table(
        "segment_climatology",
        sa.Column("coastal_segment_id", sa.Integer(), nullable=False),
        sa.Column("day_of_year", sa.Integer(), nullable=False),
        sa.Column("model_version", sa.String(length=16), nullable=False),
        sa.Column("observed", sa.Float(), nullable=False),
        sa.Column("expected_per_day", sa.Float(), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("years", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["coastal_segment_id"], ["coastal_segment.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_segment_climatology_day",
        "segment_climatology",
        ["day_of_year"],
        unique=False,
    )
    op.create_index(
        "ix_segment_climatology_dedup",
        "segment_climatology",
        ["coastal_segment_id", "day_of_year", "model_version"],
        unique=True,
    )
    op.create_table(
        "segment_forecast",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("coastal_segment_id", sa.Integer(), nullable=False),
        sa.Column("model_version", sa.String(length=16), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("persistence", sa.Float(), nullable=False),
        sa.Column("drift_index", sa.Float(), nullable=False),
        sa.Column("swell_m", sa.Float(), nullable=False),
        sa.Column("onshore_m", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["coastal_segment_id"], ["coastal_segment.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_segment_forecast_day", "segment_forecast", ["day"], unique=False
    )
    op.create_index(
        "ix_segment_forecast_dedup",
        "segment_forecast",
        ["day", "coastal_segment_id", "model_version"],
        unique=True,
    )


def downgrade() -> None:
    for table in (
        "segment_forecast",
        "segment_climatology",
        "drift_daily",
        "vessel_position",
        "stranding",
        "marine_condition",
        "job",
        "ingest_coverage",
        "grid_cell",
        "drift_release",
        "coastal_segment",
    ):
        op.drop_table(table)
    sa.Enum(name="jobstatus").drop(op.get_bind(), checkfirst=True)
